### ISSUE TITLE
execution expired (Timeout::Error)

### ISSUE THREAD

**Issue by ramontayag** [jfirebaugh/capybara-firebug#2]
I tried it out and changed 1 scenario to @firebug from @javascript, and I suddenly saw many errors like this (even on other scenarios).

```
execution expired (Timeout::Error)
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/timeout.rb:64:in `rbuf_fill'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/protocol.rb:134:in `rbuf_fill'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/protocol.rb:116:in `readuntil'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/protocol.rb:126:in `readline'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:2028:in `read_status_line'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:2017:in `read_new'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:1051:in `request'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:1037:in `request'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:543:in `start'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/net/http.rb:1035:in `request'
./features/step_definitions/web_steps.rb:20:in `/^(?:|I )am on (.+)$/'
features/manage_pages.feature:115:in `Given I have a site "Fancake", and I am the moderator "bob"'
```

**Comment by jfirebaugh** [comment]
I don't know what's causing this. Any luck debugging?

A similar stack trace is mentioned in this mailing list thread: https://groups.google.com/group/ruby-capybara/browse_thread/thread/9f45fcae2482a80c/a973b409d564d53b

**Comment by ramontayag** [comment]
Hmm no luck!

**Comment by jfirebaugh** [comment]
Unfortunately, without any means of reproducing this there's no way I can fix it.

If you can share an app or something that exhibits the problem let me know.
